CREATE OR REPLACE VIEW `data-feeder-lcd.curated.team_features_v` AS
SELECT
  year,
  team,
  wins,
  losses,
  ties,
  win_loss_perc,
  points,
  points_opp,
  points_diff,
  mov,
  g,
  total_yards,
  plays_offense,
  yds_per_play_offense,
  turnovers,
  fumbles_lost,
  first_down,
  pass_cmp,
  pass_att,
  pass_yds,
  pass_td,
  pass_int,
  pass_net_yds_per_att,
  pass_fd,
  rush_att,
  rush_yds,
  rush_td,
  rush_yds_per_att,
  rush_fd,
  penalties,
  penalties_yds,
  pen_fd,
  score_pct,
  turnover_pct,
  exp_pts_tot,
  -- Derived features
  SAFE_DIVIDE(CAST(total_yards AS FLOAT64), NULLIF(CAST(g AS FLOAT64), 0))       AS yards_per_game,
  SAFE_DIVIDE(CAST(pass_yds AS FLOAT64), NULLIF(CAST(g AS FLOAT64), 0))          AS pass_yds_per_game,
  SAFE_DIVIDE(CAST(rush_yds AS FLOAT64), NULLIF(CAST(g AS FLOAT64), 0))          AS rush_yds_per_game,
  SAFE_DIVIDE(CAST(points AS FLOAT64), NULLIF(CAST(g AS FLOAT64), 0))            AS points_per_game,
  SAFE_DIVIDE(CAST(points_opp AS FLOAT64), NULLIF(CAST(g AS FLOAT64), 0))        AS points_opp_per_game,
  SAFE_DIVIDE(CAST(pass_cmp AS FLOAT64), NULLIF(CAST(pass_att AS FLOAT64), 0))   AS pass_completion_pct,
  SAFE_DIVIDE(CAST(pass_td AS FLOAT64), NULLIF(CAST(pass_att AS FLOAT64), 0))    AS pass_td_pct,
  SAFE_DIVIDE(CAST(pass_int AS FLOAT64), NULLIF(CAST(pass_att AS FLOAT64), 0))   AS interception_pct,
  SAFE_DIVIDE(CAST(rush_yds AS FLOAT64), NULLIF(CAST(total_yards AS FLOAT64), 0)) AS rush_share,
  SAFE_DIVIDE(CAST(pass_fd AS FLOAT64), NULLIF(CAST(first_down AS FLOAT64), 0))  AS first_down_pass_pct,
  SAFE_DIVIDE(CAST(rush_fd AS FLOAT64), NULLIF(CAST(first_down AS FLOAT64), 0))  AS first_down_rush_pct,
  SAFE_DIVIDE(CAST(penalties_yds AS FLOAT64), NULLIF(CAST(g AS FLOAT64), 0))     AS penalty_yds_per_game,
  CASE WHEN wins >= 10 THEN 1 ELSE 0 END                                          AS is_playoff
FROM
  `data-feeder-lcd.curated.nfl_team_stats_2003_2023`;
